services:
  anna:
    image: ghcr.io/l8tenever/anna:latest
    container_name: anna-game-server
    ports:
      - "8080:8080"
    volumes:
      - ./public/assets/reveal_images_import:/app/public/assets/reveal_images_import
      - ./public/assets/reveal_images:/app/public/assets/reveal_images
      - ./public/assets/banners:/app/public/assets/banners
    restart: unless-stopped
